version: '3'
services:
  archive:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SMTP_SERVER = smtp.gmail.com
      - SMTP_PORT = 587
      - USERNAME = ilyasaliev1@gmail.com
      - PASSWORD = "ryuj ojbr cmrk hoev"
